# Docker Compose Override for Staging Environment
version: '3.8'

services:
  # Backend service overrides for staging
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,staging
      - LOGGING_LEVEL_COM_MINIUPS=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Frontend service overrides for staging
  frontend:
    environment:
      - NODE_ENV=staging
      - REACT_APP_API_URL=http://44.219.181.190:8081
      - REACT_APP_ENVIRONMENT=staging
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # Database overrides for staging
  upsdb:
    environment:
      - POSTGRES_DB=ups_db_staging
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123_staging
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  # Redis overrides for staging
  redis:
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_staging_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  postgres_staging_data:
    driver: local
  redis_staging_data:
    driver: local

networks:
  default:
    name: mini-ups-staging
    driver: bridge