/**
 * Shipment Entity Class
 * 
 * Function Description:
 * - Core business entity of the Mini-UPS system, recording the complete lifecycle of package transportation
 * - Manages all status changes from order placement to delivery completion
 * - Establishes relationships with user, truck, and package entities
 * 
 * Main Fields:
 * - shipmentId: Transport order ID from the Amazon system
 * - upsTrackingId: Tracking number generated by UPS
 * - status: Transport status (CREATED/PICKED_UP/IN_TRANSIT/DELIVERED, etc.)
 * - truck: Assigned transport truck
 * - destinations: Target address coordinates and detailed address
 * 
 * Database Design:
 * - Table name: shipments
 * - Indexes: shipment_id, tracking_id, status, user_id
 * - Foreign keys: user_id (user), truck_id (truck)
 * 
 * Business Process:
 * 1. Amazon creates transport order
 * 2. UPS assigns truck and generates tracking number
 * 3. Truck goes to pickup point
 * 4. Real-time location updates during transport
 * 5. Delivery completed upon reaching destination
 * 
 *
 
 */
package com.miniups.model.entity;

import com.miniups.model.enums.ShipmentStatus;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class Shipment extends BaseEntity {
    
    @NotBlank
    @Size(max = 100)
    private String shipmentId;
    
    @Size(max = 100)
    private String upsTrackingId;
    
    @Size(max = 100)
    private String amazonOrderId;
    
    private String warehouseId;
    
    private ShipmentStatus status = ShipmentStatus.CREATED;
    
    @NotNull
    private Integer originX;
    
    @NotNull
    private Integer originY;
    
    @NotNull
    private Integer destX;
    
    @NotNull
    private Integer destY;
    
    private BigDecimal weight;
    
    private LocalDateTime estimatedDelivery;
    
    private LocalDateTime actualDelivery;
    
    private LocalDateTime pickupTime;
    
    private Long worldId;
    
    private String deliveryAddress;
    
    private String deliveryCity;
    
    private String deliveryZipCode;

    // Foreign key fields
    private Long userId;

    private Long truckId;

    // Transient relationships (loaded separately if needed)
    private User user;

    private Truck truck;

    private List<ShipmentPackage> packages = new ArrayList<>();

    private List<ShipmentStatusHistory> statusHistory = new ArrayList<>();

    private List<AddressChange> addressChanges = new ArrayList<>();
    
    // Constructors
    public Shipment() {}
    
    public Shipment(String shipmentId, Integer originX, Integer originY, 
                   Integer destX, Integer destY) {
        this.shipmentId = shipmentId;
        this.originX = originX;
        this.originY = originY;
        this.destX = destX;
        this.destY = destY;
    }
    
    // Getters and Setters
    public String getShipmentId() {
        return shipmentId;
    }
    
    public void setShipmentId(String shipmentId) {
        this.shipmentId = shipmentId;
    }
    
    public String getUpsTrackingId() {
        return upsTrackingId;
    }
    
    public void setUpsTrackingId(String upsTrackingId) {
        this.upsTrackingId = upsTrackingId;
    }
    
    public String getAmazonOrderId() {
        return amazonOrderId;
    }
    
    public void setAmazonOrderId(String amazonOrderId) {
        this.amazonOrderId = amazonOrderId;
    }
    
    public String getWarehouseId() {
        return warehouseId;
    }
    
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }
    
    public ShipmentStatus getStatus() {
        return status;
    }
    
    public void setStatus(ShipmentStatus status) {
        this.status = status;
    }
    
    public Integer getOriginX() {
        return originX;
    }
    
    public void setOriginX(Integer originX) {
        this.originX = originX;
    }
    
    public Integer getOriginY() {
        return originY;
    }
    
    public void setOriginY(Integer originY) {
        this.originY = originY;
    }
    
    public Integer getDestX() {
        return destX;
    }
    
    public void setDestX(Integer destX) {
        this.destX = destX;
    }
    
    public Integer getDestY() {
        return destY;
    }
    
    public void setDestY(Integer destY) {
        this.destY = destY;
    }
    
    public BigDecimal getWeight() {
        return weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    
    public LocalDateTime getEstimatedDelivery() {
        return estimatedDelivery;
    }
    
    public void setEstimatedDelivery(LocalDateTime estimatedDelivery) {
        this.estimatedDelivery = estimatedDelivery;
    }
    
    public LocalDateTime getActualDelivery() {
        return actualDelivery;
    }
    
    public void setActualDelivery(LocalDateTime actualDelivery) {
        this.actualDelivery = actualDelivery;
    }
    
    public LocalDateTime getPickupTime() {
        return pickupTime;
    }
    
    public void setPickupTime(LocalDateTime pickupTime) {
        this.pickupTime = pickupTime;
    }
    
    public Long getWorldId() {
        return worldId;
    }
    
    public void setWorldId(Long worldId) {
        this.worldId = worldId;
    }
    
    public String getDeliveryAddress() {
        return deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    
    public String getDeliveryCity() {
        return deliveryCity;
    }
    
    public void setDeliveryCity(String deliveryCity) {
        this.deliveryCity = deliveryCity;
    }
    
    public String getDeliveryZipCode() {
        return deliveryZipCode;
    }
    
    public void setDeliveryZipCode(String deliveryZipCode) {
        this.deliveryZipCode = deliveryZipCode;
    }
    
    public User getUser() {
        return user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public Truck getTruck() {
        return truck;
    }
    
    public void setTruck(Truck truck) {
        this.truck = truck;
    }
    
    public List<ShipmentPackage> getPackages() {
        return packages;
    }
    
    public void setPackages(List<ShipmentPackage> packages) {
        this.packages = packages;
    }
    
    public List<ShipmentStatusHistory> getStatusHistory() {
        return statusHistory;
    }
    
    public void setStatusHistory(List<ShipmentStatusHistory> statusHistory) {
        this.statusHistory = statusHistory;
    }
    
    public List<AddressChange> getAddressChanges() {
        return addressChanges;
    }
    
    public void setAddressChanges(List<AddressChange> addressChanges) {
        this.addressChanges = addressChanges;
    }
    
    // Helper methods
    public boolean canChangeAddress() {
        return status == ShipmentStatus.CREATED || 
               status == ShipmentStatus.PICKED_UP || 
               status == ShipmentStatus.IN_TRANSIT;
    }
    
    public void updateStatus(ShipmentStatus newStatus) {
        this.status = newStatus;
        // Note: Status history is now managed by TrackingService to avoid duplication
    }
}