spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ups_db
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  redis:
    host: localhost
    port: 6380

jwt:
  secret: dev-secret-key-for-jwt-token-generation-miniups-2024

logging:
  level:
    com.miniups: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

world-simulator:
  host: localhost
  port: 12345

amazon:
  base-url: http://localhost:8080