spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mini_ups}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6380}
    password: ${REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET:YourProductionSecretKeyThatShouldBeAtLeast256BitsLong}

world-simulator:
  host: ${WORLD_SIMULATOR_HOST:world-simulator}
  port: ${WORLD_SIMULATOR_PORT:12345}

amazon:
  base-url: ${AMAZON_BASE_URL:http://amazon-service:8080}

logging:
  level:
    com.miniups: INFO
    org.hibernate.SQL: WARN