# =======================================
# Pull Request CI Pipeline for Frontend
# =======================================

name: Frontend PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pr.yml'

env:
  NODE_VERSION: '20'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # =======================================
  # Validate PR Job
  # =======================================
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Type checking
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test -- --coverage --reporter=verbose

      - name: Build for preview
        run: npm run build:staging
        env:
          VITE_API_BASE_URL: https://api-staging.mini-ups.dev
          VITE_WS_BASE_URL: wss://api-staging.mini-ups.dev
          VITE_APP_VERSION: ${{ github.sha }}
          VITE_ENABLE_ANALYTICS: false
          VITE_LOG_LEVEL: info

      - name: Bundle size analysis
        run: npm run size-limit

      - name: Upload preview build
        uses: actions/upload-artifact@v4
        with:
          name: preview-build-${{ github.event.number }}
          path: ./frontend/dist
          retention-days: 3

      - name: Comment PR with build info
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read build report if it exists
            let buildInfo = 'Build completed successfully! ✅';
            const reportPath = './frontend/dist/build-report.json';
            
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              buildInfo = `
            ## 📦 Build Analysis
            
            - **Total bundle size:** ${report.total_size_formatted}
            - **JavaScript files:** ${report.files.javascript.count} (${(report.files.javascript.total_size / 1024).toFixed(1)} KB)
            - **CSS files:** ${report.files.css.count} (${(report.files.css.total_size / 1024).toFixed(1)} KB)
            - **Images:** ${report.files.images.count} (${(report.files.images.total_size / 1024).toFixed(1)} KB)
            - **Within size limits:** ${report.within_limits ? '✅' : '❌'}
            
            Preview deployment will be available after merge to staging.
            `;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: buildInfo
            });

  # =======================================
  # Visual Regression Testing
  # =======================================
  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    needs: [validate]
    if: github.event.pull_request.draft == false
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download preview build
        uses: actions/download-artifact@v4
        with:
          name: preview-build-${{ github.event.number }}
          path: ./frontend/dist

      - name: Start preview server
        run: |
          npx serve -s dist -l 3000 &
          sleep 5

      - name: Run visual regression tests
        uses: lost-pixel/lost-pixel@v3.16.0
        with:
          config: './frontend/lost-pixel.config.ts'
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}

  # =======================================
  # Security Analysis
  # =======================================
  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          languages: javascript
          source-root: ./frontend