spring:
  
  # Database Configuration for Tests
  # Uses H2 for fast unit tests, PostgreSQL for CI integration tests
  datasource:
    url: ${TEST_DATABASE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${TEST_DATABASE_DRIVER:org.h2.Driver}
    username: ${TEST_DATABASE_USERNAME:sa}
    password: ${TEST_DATABASE_PASSWORD:password}
  
  # JPA Configuration
  jpa:
    database-platform: ${TEST_DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          batch_size: 25
        hbm2ddl:
          auto: create-drop
  
  # Redis Configuration for Testing
  redis:
    host: ${TEST_REDIS_HOST:localhost}
    port: ${TEST_REDIS_PORT:6370}  # Different port for local testing
    timeout: 2000ms
  
  # RabbitMQ Configuration (Disabled for Testing)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  # Auto-configuration exclusions for testing
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  
  # Logging Configuration
  logging:
    level:
      com.miniups: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

# JWT Configuration for Testing
jwt:
  secret: test-secret-key-for-unit-tests-that-is-long-enough-for-security
  expiration: 3600000  # 1 hour

# World Simulator Mock Configuration
world:
  simulator:
    host: localhost
    port: 12345
    connection-timeout: 5000
    read-timeout: 10000
    enabled: false  # Disabled for unit tests

# Amazon Integration Mock Configuration
amazon:
  api:
    url: http://localhost:8080
    timeout: 5000
    enabled: false  # Disabled for unit tests

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always